[package]
name = "HockeyStats"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
tokio = { version = "1", features = ["full"] }
scraper = "0.13"
regex = "1.11.1"
chrono = "0.4.38"
